define: &containerPort 80

# application
app:
  servicePort: 80
  containerPort: *containerPort

# deployment
deployment:
  memoryRequest: null
  cpuRequest: null
  memoryLimit: null
  cpuLimit: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

# container
image:
  repository:
    name: null
    isPrivate: false
    secretName: null
  name: nginx
  tag: latest
  pullPolicy: Always

# ingress
ingress:
  enabled: false
  hostName: toto.lan
  tls:
    enabled: true
    secretName: ""
  # For Ingress CRD
  ingressClassName: istio
  # For IngressRoute CRD
  isIngressRoute: false
  entrypoint: websecure
  certResolver: mycertresolver # leave empty if you don't use, tls.enabled must be true and secretName must me empty

    
# env variables
variables:
  secret: {}
#    user: "qjoly"
#    password: "hugepassword"
  nonSecret: {}
#    author: qjoly
#    app: 1

# horizontal autoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  avgCpuUtilization: 50

# startupProbe
startupProbeEnabled: false
startupProbe: {}
  # httpGet:
  #   path: "/"
  #   port: *containerPort
  # periodSeconds: 10
  # failureThreshold: 20
  # timeoutSeconds: 1

# readinessProbe
readinessProbeEnabled: false
readinessProbe: {}
  # httpGet:
  #   path: "/"
  #   port: *containerPort
  # initialDelaySeconds: 20
  # periodSeconds: 30
  # failureThreshold: 2
  # timeoutSeconds: 3

# livenessProbe
livenessProbeEnabled: false
livenessProbe: {}
  # enabled: true
  # httpGet:
  #   path: "/"
  #   port: *containerPort
  # initialDelaySeconds: 20
  # periodSeconds: 60
  # failureThreshold: 1
  # timeoutSeconds: 3


persistence:
  enabled: false
  volumes: {}
    # - name: "data"
    #   storageClassName: "longhorn" # leave empty if you want to use default
    #   size: "5Gi" # We recommend to allocate a minimum of 1GB if you do not use attachments
    #   pvcClaim: "" # leave empty unless if you want to use an existing PVC
    #   containerMount: "/data"
    # - name: "logs"
    #   storageClassName: "" # leave empty if you want to use default
    #   size: "1Gi" # We recommend to allocate a minimum of 1GB if you do not use attachments
    #   pvcClaim: "" # leave empty unless if you want to use an existing PVC
    #   containerMount: "/var/log"
    # - name: "temp"
    #   pvcClaim: "existing" # leave empty unless if you want to use an existing PVC
    #   containerMount: "/testest"
tests:
  classicHttp: # default helm test method 
    enabled: true
  curlHostHeader: # curl using ingress.hostName as Host in header
    enabled: true
    path: ""

